DROP TABLE IF EXISTS url_checks;
DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at timestamp NOT NULL
);

CREATE TABLE url_checks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url_id BIGINT NOT NULL,
    status_code int,
    h1 VARCHAR(255),
    title VARCHAR(255),
    description text,
    created_at timestamp NOT NULL,
    CONSTRAINT fk_url_checks_url_id
        FOREIGN KEY (url_id) REFERENCES urls(id) ON DELETE CASCADE
);
